In [1]:
import numpy as np


In [2]:
revenue_in_USD = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])

In [3]:
revenue_in_npr = 130*revenue_in_USD
revenue_in_npr

array([[26000, 28600, 32500],
       [ 8840, 10270, 13650],
       [14300, 18200, 23400],
       [10400, 11050, 11700]])

In [9]:
units_sold = np.array([[1,2,3],[4,5,6],[7,8,9]])
price_per_unit = np.array([10,20,30])
result = np.dot(price_per_unit,units_sold)
result

array([300, 360, 420])

In [6]:
price_per_unit*units_sold

array([[ 10,  40,  90],
       [ 40, 100, 180],
       [ 70, 160, 270]])

In [11]:
np.dot(units_sold,price_per_unit)

array([140, 320, 500])